"""
Detailed PyBAMM parameter set configurations.

This module provides comprehensive information about available parameter sets
and their specific parameters for different battery chemistries.

Reference: https://docs.pybamm.org/en/stable/source/api/parameters/parameter_sets.html
"""
from typing import Dict, List, Any, Optional


# =============================================================================
# CHEMISTRY-SPECIFIC DEFAULT PARAMETERS
# These are the key parameters that typically differ between chemistries
# =============================================================================

LFP_DEFAULTS = {
    "description": "Lithium Iron Phosphate (LiFePO4) - safe, long cycle life",
    "typical_parameters": {
        "Nominal cell capacity [A.h]": 2.3,
        "Lower voltage cut-off [V]": 2.5,
        "Upper voltage cut-off [V]": 3.65,
        "Nominal voltage [V]": 3.2,
        "Maximum C-rate": 3.0,
        "Typical cycle life": "2000-5000 cycles",
    },
    "characteristics": {
        "energy_density": "Low-Medium",
        "power_density": "Medium",
        "safety": "Excellent",
        "cost": "Medium",
        "temperature_range": "-20°C to 60°C",
    },
    "recommended_parameter_sets": ["Prada2013"],
}

NMC_DEFAULTS = {
    "description": "Lithium Nickel Manganese Cobalt Oxide - high energy density",
    "typical_parameters": {
        "Nominal cell capacity [A.h]": 5.0,
        "Lower voltage cut-off [V]": 2.5,
        "Upper voltage cut-off [V]": 4.2,
        "Nominal voltage [V]": 3.7,
        "Maximum C-rate": 2.0,
        "Typical cycle life": "1000-2000 cycles",
    },
    "characteristics": {
        "energy_density": "High",
        "power_density": "Medium-High",
        "safety": "Good",
        "cost": "High",
        "temperature_range": "-20°C to 55°C",
    },
    "recommended_parameter_sets": ["Chen2020", "ORegan2022", "Ai2020", "Mohtat2020"],
}

NCA_DEFAULTS = {
    "description": "Lithium Nickel Cobalt Aluminum Oxide - highest energy density",
    "typical_parameters": {
        "Nominal cell capacity [A.h]": 3.5,
        "Lower voltage cut-off [V]": 2.5,
        "Upper voltage cut-off [V]": 4.2,
        "Nominal voltage [V]": 3.6,
        "Maximum C-rate": 2.0,
        "Typical cycle life": "500-1500 cycles",
    },
    "characteristics": {
        "energy_density": "Very High",
        "power_density": "High",
        "safety": "Moderate",
        "cost": "High",
        "temperature_range": "-20°C to 50°C",
    },
    "recommended_parameter_sets": ["NCA_Kim2011"],
}

LCO_DEFAULTS = {
    "description": "Lithium Cobalt Oxide - high energy, consumer electronics",
    "typical_parameters": {
        "Nominal cell capacity [A.h]": 2.6,
        "Lower voltage cut-off [V]": 3.0,
        "Upper voltage cut-off [V]": 4.2,
        "Nominal voltage [V]": 3.7,
        "Maximum C-rate": 1.0,
        "Typical cycle life": "500-1000 cycles",
    },
    "characteristics": {
        "energy_density": "High",
        "power_density": "Medium",
        "safety": "Moderate",
        "cost": "Very High",
        "temperature_range": "-20°C to 45°C",
    },
    "recommended_parameter_sets": ["Marquis2019", "Ecker2015", "Ramadass2004", "Xu2019"],
}

SODIUM_ION_DEFAULTS = {
    "description": "Sodium-ion - low cost, abundant materials",
    "typical_parameters": {
        "Nominal cell capacity [A.h]": 1.0,
        "Lower voltage cut-off [V]": 2.0,
        "Upper voltage cut-off [V]": 4.0,
        "Nominal voltage [V]": 3.3,
        "Maximum C-rate": 1.0,
        "Typical cycle life": "1000-3000 cycles",
    },
    "characteristics": {
        "energy_density": "Medium",
        "power_density": "Medium",
        "safety": "Good",
        "cost": "Low",
        "temperature_range": "-20°C to 60°C",
    },
    "recommended_parameter_sets": ["Chayambuka2022"],
}

LEAD_ACID_DEFAULTS = {
    "description": "Lead-acid - mature technology, low cost",
    "typical_parameters": {
        "Nominal cell capacity [A.h]": 17.0,
        "Lower voltage cut-off [V]": 1.75,
        "Upper voltage cut-off [V]": 2.4,
        "Nominal voltage [V]": 2.0,
        "Maximum C-rate": 0.2,
        "Typical cycle life": "200-500 cycles",
    },
    "characteristics": {
        "energy_density": "Low",
        "power_density": "Low",
        "safety": "Moderate",
        "cost": "Very Low",
        "temperature_range": "-20°C to 50°C",
    },
    "recommended_parameter_sets": ["Sulzer2019"],
}

CHEMISTRY_DEFAULTS = {
    "LFP": LFP_DEFAULTS,
    "NMC": NMC_DEFAULTS,
    "NCA": NCA_DEFAULTS,
    "LCO": LCO_DEFAULTS,
    "SODIUM_ION": SODIUM_ION_DEFAULTS,
    "LEAD_ACID": LEAD_ACID_DEFAULTS,
}


# =============================================================================
# DETAILED PARAMETER SET INFORMATION
# =============================================================================

PARAMETER_SET_DETAILS = {
    "Prada2013": {
        "full_name": "Prada et al. 2013 LFP Parameters",
        "chemistry": "LFP",
        "cell_type": "cylindrical",
        "cell_format": "26650",
        "reference": "Prada et al., J. Electrochem. Soc., 160(4), A542-A554 (2013)",
        "doi": "10.1149/2.023304jes",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 2.3,
            "Lower voltage cut-off [V]": 2.0,
            "Upper voltage cut-off [V]": 3.6,
            "Electrode height [m]": 0.6,
            "Electrode width [m]": 0.3,
            "Negative electrode thickness [m]": 3.4e-05,
            "Positive electrode thickness [m]": 8e-05,
            "Separator thickness [m]": 2.5e-05,
            "Negative particle radius [m]": 5e-06,
            "Positive particle radius [m]": 5e-08,
            "Negative electrode porosity": 0.36,
            "Positive electrode porosity": 0.426,
            "Negative electrode active material volume fraction": 0.58,
            "Positive electrode active material volume fraction": 0.374,
            "Maximum concentration in negative electrode [mol.m-3]": 30555,
            "Maximum concentration in positive electrode [mol.m-3]": 22806,
            "Negative electrode conductivity [S.m-1]": 215.0,
            "Positive electrode conductivity [S.m-1]": 0.338,
            "Initial concentration in electrolyte [mol.m-3]": 1200.0,
            "Cation transference number": 0.36,
            "Reference temperature [K]": 298.15,
        },
        "validated_conditions": {
            "temperature_range": "5°C to 45°C",
            "c_rate_range": "C/25 to 5C",
        },
    },
    "Chen2020": {
        "full_name": "Chen et al. 2020 NMC Parameters (LG M50)",
        "chemistry": "NMC",
        "cell_type": "cylindrical",
        "cell_format": "21700",
        "reference": "Chen et al., J. Electrochem. Soc., 167(8), 080534 (2020)",
        "doi": "10.1149/1945-7111/ab9050",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 5.0,
            "Lower voltage cut-off [V]": 2.5,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.065,
            "Electrode width [m]": 1.58,
            "Negative current collector thickness [m]": 1.2e-05,
            "Negative electrode thickness [m]": 8.52e-05,
            "Separator thickness [m]": 1.2e-05,
            "Positive electrode thickness [m]": 7.56e-05,
            "Positive current collector thickness [m]": 1.6e-05,
            "Negative particle radius [m]": 5.86e-06,
            "Positive particle radius [m]": 5.22e-06,
            "Negative electrode porosity": 0.25,
            "Positive electrode porosity": 0.335,
            "Negative electrode active material volume fraction": 0.75,
            "Positive electrode active material volume fraction": 0.665,
            "Maximum concentration in negative electrode [mol.m-3]": 33133.0,
            "Maximum concentration in positive electrode [mol.m-3]": 63104.0,
            "Negative electrode conductivity [S.m-1]": 215.0,
            "Positive electrode conductivity [S.m-1]": 0.18,
            "Negative particle diffusivity [m2.s-1]": 3.3e-14,
            "Positive particle diffusivity [m2.s-1]": 4e-15,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Cation transference number": 0.2594,
            "Reference temperature [K]": 298.15,
            "Cell cooling surface area [m2]": 0.00531,
            "Cell volume [m3]": 2.42e-05,
        },
        "validated_conditions": {
            "temperature_range": "0°C to 45°C",
            "c_rate_range": "C/20 to 4C",
        },
    },
    "ORegan2022": {
        "full_name": "O'Regan et al. 2022 NMC Parameters (LG M50)",
        "chemistry": "NMC",
        "cell_type": "cylindrical",
        "cell_format": "21700",
        "reference": "O'Regan et al., Electrochim. Acta, 425, 140700 (2022)",
        "doi": "10.1016/j.electacta.2022.140700",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 5.0,
            "Lower voltage cut-off [V]": 2.5,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.065,
            "Electrode width [m]": 1.58,
            "Negative electrode thickness [m]": 8.52e-05,
            "Separator thickness [m]": 1.2e-05,
            "Positive electrode thickness [m]": 7.56e-05,
            "Negative particle radius [m]": 5.86e-06,
            "Positive particle radius [m]": 5.22e-06,
            "Negative electrode porosity": 0.25,
            "Positive electrode porosity": 0.335,
            "Maximum concentration in negative electrode [mol.m-3]": 33133.0,
            "Maximum concentration in positive electrode [mol.m-3]": 63104.0,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Reference temperature [K]": 298.15,
        },
        "validated_conditions": {
            "temperature_range": "-10°C to 45°C",
            "c_rate_range": "C/3 to 3C",
        },
        "special_features": ["Thermal parameterization", "Drive cycle validation"],
    },
    "NCA_Kim2011": {
        "full_name": "Kim et al. 2011 NCA Parameters",
        "chemistry": "NCA",
        "cell_type": "pouch",
        "cell_format": "Nominal Design",
        "reference": "Kim et al., J. Electrochem. Soc., 158(8), A955-A969 (2011)",
        "doi": "10.1149/1.3597614",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 0.43,
            "Lower voltage cut-off [V]": 2.7,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.2,
            "Electrode width [m]": 0.14,
            "Negative current collector thickness [m]": 1e-05,
            "Negative electrode thickness [m]": 7e-05,
            "Separator thickness [m]": 2.5e-05,
            "Positive electrode thickness [m]": 5e-05,
            "Positive current collector thickness [m]": 1e-05,
            "Negative particle radius [m]": 5.083e-07,
            "Positive particle radius [m]": 1.633e-06,
            "Negative electrode porosity": 0.4,
            "Positive electrode porosity": 0.4,
            "Negative electrode active material volume fraction": 0.51,
            "Positive electrode active material volume fraction": 0.41,
            "Maximum concentration in negative electrode [mol.m-3]": 28700.0,
            "Maximum concentration in positive electrode [mol.m-3]": 49000.0,
            "Negative electrode conductivity [S.m-1]": 100.0,
            "Positive electrode conductivity [S.m-1]": 10.0,
            "Initial concentration in electrolyte [mol.m-3]": 1200.0,
            "Cation transference number": 0.4,
            "Reference temperature [K]": 298.15,
            "Cell cooling surface area [m2]": 0.0561,
            "Cell volume [m3]": 4.62e-06,
        },
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/2 to 3C",
        },
    },
    "Marquis2019": {
        "full_name": "Marquis et al. 2019 LCO Parameters",
        "chemistry": "LCO",
        "cell_type": "pouch",
        "cell_format": "Kokam SLPB78205130H",
        "reference": "Marquis et al., J. Electrochem. Soc., 166(15), A3693-A3706 (2019)",
        "doi": "10.1149/2.0011915jes",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 0.680616,
            "Lower voltage cut-off [V]": 3.105,
            "Upper voltage cut-off [V]": 4.1,
            "Electrode height [m]": 0.137,
            "Electrode width [m]": 0.207,
            "Negative current collector thickness [m]": 2.5e-05,
            "Negative electrode thickness [m]": 0.0001,
            "Separator thickness [m]": 2.5e-05,
            "Positive electrode thickness [m]": 0.0001,
            "Positive current collector thickness [m]": 2.5e-05,
            "Negative particle radius [m]": 1e-05,
            "Positive particle radius [m]": 1e-05,
            "Negative electrode porosity": 0.3,
            "Positive electrode porosity": 0.3,
            "Negative electrode active material volume fraction": 0.6,
            "Positive electrode active material volume fraction": 0.5,
            "Maximum concentration in negative electrode [mol.m-3]": 24983.26,
            "Maximum concentration in positive electrode [mol.m-3]": 51217.93,
            "Negative electrode conductivity [S.m-1]": 100.0,
            "Positive electrode conductivity [S.m-1]": 10.0,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Cation transference number": 0.4,
            "Reference temperature [K]": 298.15,
            "Cell cooling surface area [m2]": 0.0569,
            "Cell volume [m3]": 7.8e-06,
        },
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/10 to 1C",
        },
    },
    "Ecker2015": {
        "full_name": "Ecker et al. 2015 LCO Parameters (Kokam)",
        "chemistry": "LCO",
        "cell_type": "pouch",
        "cell_format": "SLPB 75106100",
        "reference": "Ecker et al., J. Electrochem. Soc., 162(9), A1836-A1848 (2015)",
        "doi": "10.1149/2.0551509jes",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 0.15625,
            "Lower voltage cut-off [V]": 2.5,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.101,
            "Electrode width [m]": 0.085,
            "Negative current collector thickness [m]": 1.4e-05,
            "Negative electrode thickness [m]": 7.4e-05,
            "Separator thickness [m]": 2e-05,
            "Positive electrode thickness [m]": 5.4e-05,
            "Positive current collector thickness [m]": 1.5e-05,
            "Negative particle radius [m]": 1.37e-05,
            "Positive particle radius [m]": 6.5e-06,
            "Negative electrode porosity": 0.329,
            "Positive electrode porosity": 0.296,
            "Negative electrode active material volume fraction": 0.372403,
            "Positive electrode active material volume fraction": 0.40832,
            "Maximum concentration in negative electrode [mol.m-3]": 31920.0,
            "Maximum concentration in positive electrode [mol.m-3]": 48580.0,
            "Negative electrode conductivity [S.m-1]": 14.0,
            "Positive electrode conductivity [S.m-1]": 68.1,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Cation transference number": 0.26,
            "Reference temperature [K]": 296.15,
            "Cell cooling surface area [m2]": 0.0172,
            "Cell volume [m3]": 1.52e-06,
        },
        "validated_conditions": {
            "temperature_range": "25°C to 40°C",
            "c_rate_range": "C/10 to 2C",
        },
        "special_features": ["Comprehensive validation dataset", "Lithium plating parameters"],
    },
    "Ai2020": {
        "full_name": "Ai et al. 2020 NMC Parameters (Enertech)",
        "chemistry": "NMC",
        "cell_type": "pouch",
        "cell_format": "Enertech",
        "reference": "Ai et al., J. Electrochem. Soc., 167(1), 013512 (2020)",
        "doi": "10.1149/2.0122001jes",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 12.5,
            "Lower voltage cut-off [V]": 2.7,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.1,
            "Electrode width [m]": 0.21,
            "Negative electrode thickness [m]": 7.65e-05,
            "Separator thickness [m]": 1.2e-05,
            "Positive electrode thickness [m]": 6.6e-05,
            "Negative particle radius [m]": 5.86e-06,
            "Positive particle radius [m]": 5.22e-06,
            "Negative electrode porosity": 0.25,
            "Positive electrode porosity": 0.335,
            "Maximum concentration in negative electrode [mol.m-3]": 33133.0,
            "Maximum concentration in positive electrode [mol.m-3]": 63104.0,
            "Negative electrode conductivity [S.m-1]": 215.0,
            "Positive electrode conductivity [S.m-1]": 0.18,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Reference temperature [K]": 298.15,
        },
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/20 to 3C",
        },
        "special_features": ["Large format cell", "Thermal characterization", "SEI parameters"],
    },
    "Ramadass2004": {
        "full_name": "Ramadass et al. 2004 LCO Parameters (Sony)",
        "chemistry": "LCO",
        "cell_type": "cylindrical",
        "cell_format": "18650",
        "reference": "Ramadass et al., J. Electrochem. Soc., 151(2), A196-A203 (2004)",
        "doi": "10.1149/1.1634273",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 0.680616,
            "Lower voltage cut-off [V]": 3.105,
            "Upper voltage cut-off [V]": 4.1,
            "Electrode height [m]": 0.137,
            "Electrode width [m]": 0.207,
            "Negative electrode thickness [m]": 0.0001,
            "Separator thickness [m]": 2.5e-05,
            "Positive electrode thickness [m]": 0.0001,
            "Negative particle radius [m]": 1e-05,
            "Positive particle radius [m]": 1e-05,
            "Negative electrode porosity": 0.3,
            "Positive electrode porosity": 0.3,
            "Maximum concentration in negative electrode [mol.m-3]": 24983.26,
            "Maximum concentration in positive electrode [mol.m-3]": 51217.93,
            "Negative electrode conductivity [S.m-1]": 100.0,
            "Positive electrode conductivity [S.m-1]": 10.0,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Cation transference number": 0.4,
            "Reference temperature [K]": 298.15,
        },
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/6 to 2C",
        },
        "special_features": ["Classic reference parameter set", "SEI growth parameters"],
    },
    "Mohtat2020": {
        "full_name": "Mohtat et al. 2020 NMC532 Parameters",
        "chemistry": "NMC",
        "cell_type": "pouch",
        "cell_format": "NMC532/Graphite",
        "reference": "Mohtat et al., J. Electrochem. Soc., 167(9), 090512 (2020)",
        "doi": "10.1149/1945-7111/ab8f59",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 0.490,
            "Lower voltage cut-off [V]": 2.8,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.065,
            "Electrode width [m]": 1.58,
            "Negative electrode thickness [m]": 7e-05,
            "Separator thickness [m]": 2.5e-05,
            "Positive electrode thickness [m]": 6.5e-05,
            "Negative particle radius [m]": 5.86e-06,
            "Positive particle radius [m]": 5.22e-06,
            "Negative electrode porosity": 0.3,
            "Positive electrode porosity": 0.3,
            "Maximum concentration in negative electrode [mol.m-3]": 33133.0,
            "Maximum concentration in positive electrode [mol.m-3]": 63104.0,
            "Negative electrode conductivity [S.m-1]": 215.0,
            "Positive electrode conductivity [S.m-1]": 0.18,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Reference temperature [K]": 298.15,
        },
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/20 to 2C",
        },
        "special_features": ["SEI parameters", "Lithium plating parameters"],
    },
    "Xu2019": {
        "full_name": "Xu et al. 2019 Degradation Parameters",
        "chemistry": "LCO",
        "cell_type": "half-cell",
        "cell_format": "Kokam SLPB78205130H",
        "reference": "Xu et al., J. Electrochem. Soc., 166(14), A3456-A3463 (2019)",
        "doi": "10.1149/2.0501914jes",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 0.680616,
            "Lower voltage cut-off [V]": 3.105,
            "Upper voltage cut-off [V]": 4.1,
            "Negative electrode thickness [m]": 0.0001,
            "Separator thickness [m]": 2.5e-05,
            "Positive electrode thickness [m]": 0.0001,
            "Negative particle radius [m]": 1e-05,
            "Positive particle radius [m]": 1e-05,
            "Maximum concentration in negative electrode [mol.m-3]": 24983.26,
            "Maximum concentration in positive electrode [mol.m-3]": 51217.93,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Reference temperature [K]": 298.15,
        },
        "special_features": ["Degradation modeling", "Dead lithium growth", "Capacity loss modeling"],
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/20 to 1C",
        },
    },
    # =========================================================================
    # COMPOSITE ELECTRODE PARAMETER SETS
    # =========================================================================
    "Chen2020_composite": {
        "full_name": "Chen et al. 2020 Composite Si/Graphite Parameters",
        "chemistry": "NMC",
        "cell_type": "cylindrical",
        "cell_format": "21700",
        "reference": "Ai et al., J. Power Sources, 527, 231142 (2022)",
        "doi": "10.1016/j.jpowsour.2022.231142",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 5.0,
            "Lower voltage cut-off [V]": 2.5,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.065,
            "Electrode width [m]": 1.58,
            "Negative electrode thickness [m]": 8.52e-05,
            "Separator thickness [m]": 1.2e-05,
            "Positive electrode thickness [m]": 7.56e-05,
            "Primary negative particle radius [m]": 5.86e-06,
            "Secondary negative particle radius [m]": 1.52e-06,
            "Positive particle radius [m]": 5.22e-06,
            "Primary negative electrode porosity": 0.25,
            "Secondary negative electrode porosity": 0.5,
            "Positive electrode porosity": 0.335,
            "Maximum concentration in negative electrode [mol.m-3]": 33133.0,
            "Maximum concentration in positive electrode [mol.m-3]": 63104.0,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Reference temperature [K]": 298.15,
        },
        "special_features": [
            "Silicon/graphite composite negative electrode",
            "Composite SEI modeling",
            "Based on Chen2020 LG M50 cell",
            "Two-phase negative electrode model",
        ],
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/20 to 2C",
        },
    },
    # =========================================================================
    # HALF-CELL PARAMETER SETS
    # =========================================================================
    "Ecker2015_graphite_halfcell": {
        "full_name": "Ecker et al. 2015 Graphite Half-Cell Parameters",
        "chemistry": "LCO",
        "cell_type": "half-cell",
        "cell_format": "Kokam SLPB 75106100",
        "reference": "Ecker et al., J. Electrochem. Soc., 162(9), A1836-A1848 (2015)",
        "doi": "10.1149/2.0551509jes",
        "key_parameters": {
            "Lower voltage cut-off [V]": 0.01,
            "Upper voltage cut-off [V]": 1.5,
            "Electrode height [m]": 0.101,
            "Electrode width [m]": 0.085,
            "Negative electrode thickness [m]": 7.4e-05,
            "Separator thickness [m]": 2e-05,
            "Negative particle radius [m]": 1.37e-05,
            "Negative electrode porosity": 0.329,
            "Negative electrode active material volume fraction": 0.372403,
            "Maximum concentration in negative electrode [mol.m-3]": 31920.0,
            "Negative electrode conductivity [S.m-1]": 14.0,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Cation transference number": 0.26,
            "Reference temperature [K]": 296.15,
        },
        "special_features": [
            "Graphite half-cell configuration",
            "Li metal counter electrode",
            "SEI growth parameters",
        ],
        "validated_conditions": {
            "temperature_range": "25°C to 40°C",
            "c_rate_range": "C/10 to 2C",
        },
    },
    "OKane2022_graphite_SiOx_halfcell": {
        "full_name": "O'Kane et al. 2022 Graphite+SiOx Half-Cell Parameters",
        "chemistry": "NMC",
        "cell_type": "half-cell",
        "cell_format": "LG M50 derived",
        "reference": "O'Kane et al., Phys. Chem. Chem. Phys., 24, 7909-7922 (2022)",
        "doi": "10.1039/D2CP00417H",
        "key_parameters": {
            "Lower voltage cut-off [V]": 0.01,
            "Upper voltage cut-off [V]": 1.5,
            "Electrode height [m]": 0.065,
            "Electrode width [m]": 1.58,
            "Negative electrode thickness [m]": 8.52e-05,
            "Separator thickness [m]": 1.2e-05,
            "Negative particle radius [m]": 5.86e-06,
            "Negative electrode porosity": 0.25,
            "Negative electrode active material volume fraction": 0.75,
            "Maximum concentration in negative electrode [mol.m-3]": 33133.0,
            "Negative electrode conductivity [S.m-1]": 215.0,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Cation transference number": 0.2594,
            "Reference temperature [K]": 298.15,
        },
        "special_features": [
            "Graphite+SiOx composite negative electrode",
            "Half-cell configuration",
            "Degradation modeling",
            "SEI and plating parameters",
        ],
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/3 to 1C",
        },
    },
    # =========================================================================
    # DEGRADATION-FOCUSED PARAMETER SETS
    # =========================================================================
    "OKane2022": {
        "full_name": "O'Kane et al. 2022 Degradation Parameters (LG M50)",
        "chemistry": "NMC",
        "cell_type": "cylindrical",
        "cell_format": "21700",
        "reference": "O'Kane et al., Phys. Chem. Chem. Phys., 24, 7909-7922 (2022)",
        "doi": "10.1039/D2CP00417H",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 5.0,
            "Lower voltage cut-off [V]": 2.5,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.065,
            "Electrode width [m]": 1.58,
            "Negative electrode thickness [m]": 8.52e-05,
            "Separator thickness [m]": 1.2e-05,
            "Positive electrode thickness [m]": 7.56e-05,
            "Negative particle radius [m]": 5.86e-06,
            "Positive particle radius [m]": 5.22e-06,
            "Negative electrode porosity": 0.25,
            "Positive electrode porosity": 0.335,
            "Maximum concentration in negative electrode [mol.m-3]": 33133.0,
            "Maximum concentration in positive electrode [mol.m-3]": 63104.0,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Cation transference number": 0.2594,
            "Reference temperature [K]": 298.15,
            "Initial SEI thickness [m]": 5e-09,
            "SEI kinetic rate constant [m.s-1]": 1e-12,
            "Lithium plating kinetic rate constant [m.s-1]": 1e-10,
        },
        "special_features": [
            "Comprehensive degradation modeling",
            "SEI growth",
            "Lithium plating (reversible/irreversible/partially reversible)",
            "Loss of active material",
            "Based on Chen2020 cell",
        ],
        "validated_conditions": {
            "temperature_range": "-10°C to 45°C",
            "c_rate_range": "C/3 to 3C",
        },
    },
    # =========================================================================
    # MSMR (MULTI-SPECIES MULTI-REACTION) PARAMETER SETS
    # =========================================================================
    "MSMR_Example": {
        "full_name": "MSMR Example Parameters (NMC622)",
        "chemistry": "NMC",
        "cell_type": "cylindrical",
        "cell_format": "21700",
        "reference": "Verbrugge et al., J. Electrochem. Soc., 164(11), A3243-A3253 (2017)",
        "doi": "10.1149/2.0341708jes",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 5.0,
            "Lower voltage cut-off [V]": 2.5,
            "Upper voltage cut-off [V]": 4.2,
            "Electrode height [m]": 0.065,
            "Electrode width [m]": 1.58,
            "Negative electrode thickness [m]": 8.52e-05,
            "Separator thickness [m]": 1.2e-05,
            "Positive electrode thickness [m]": 7.56e-05,
            "Negative particle radius [m]": 5.86e-06,
            "Positive particle radius [m]": 5.22e-06,
            "Negative electrode porosity": 0.25,
            "Positive electrode porosity": 0.335,
            "Maximum concentration in negative electrode [mol.m-3]": 28746.0,
            "Maximum concentration in positive electrode [mol.m-3]": 35380.0,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Reference temperature [K]": 298.15,
            "Number of reactions in negative electrode": 6,
            "Number of reactions in positive electrode": 4,
        },
        "special_features": [
            "Multi-Species Multi-Reaction model",
            "Thermodynamic parameters for Graphite and NMC622",
            "Example parameter set for MSMR model validation",
            "Based on LG M50 cell geometry",
        ],
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/20 to 1C",
        },
    },
    # =========================================================================
    # SODIUM-ION PARAMETER SETS
    # =========================================================================
    "Chayambuka2022": {
        "full_name": "Chayambuka et al. 2022 Sodium-Ion Parameters",
        "chemistry": "SODIUM_ION",
        "cell_type": "cylindrical",
        "cell_format": "18650",
        "reference": "Chayambuka et al., Electrochim. Acta, 404, 139764 (2022)",
        "doi": "10.1016/j.electacta.2021.139764",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 1.1,
            "Lower voltage cut-off [V]": 2.0,
            "Upper voltage cut-off [V]": 4.3,
            "Electrode height [m]": 0.065,
            "Electrode width [m]": 1.58,
            "Negative electrode thickness [m]": 7e-05,
            "Separator thickness [m]": 2.5e-05,
            "Positive electrode thickness [m]": 7e-05,
            "Negative particle radius [m]": 5e-06,
            "Positive particle radius [m]": 3e-06,
            "Negative electrode porosity": 0.3,
            "Positive electrode porosity": 0.3,
            "Maximum concentration in negative electrode [mol.m-3]": 25000.0,
            "Maximum concentration in positive electrode [mol.m-3]": 15000.0,
            "Negative electrode conductivity [S.m-1]": 10.0,
            "Positive electrode conductivity [S.m-1]": 0.1,
            "Initial concentration in electrolyte [mol.m-3]": 1000.0,
            "Cation transference number": 0.4,
            "Reference temperature [K]": 298.15,
            "Cathode material": "NVPF (Na3V2(PO4)2F3)",
            "Anode material": "Hard carbon",
        },
        "special_features": [
            "Sodium-ion battery chemistry",
            "Physics-based DFN model",
            "NVPF cathode",
            "Hard carbon anode",
            "Model validation included",
        ],
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/10 to 1C",
        },
    },
    # =========================================================================
    # LEAD-ACID PARAMETER SETS
    # =========================================================================
    "Sulzer2019": {
        "full_name": "Sulzer et al. 2019 Lead-Acid Parameters (BBOXX)",
        "chemistry": "LEAD_ACID",
        "cell_type": "flooded",
        "cell_format": "BBOXX",
        "reference": "Sulzer et al., J. Electrochem. Soc., 166(12), A2372-A2382 (2019)",
        "doi": "10.1149/2.0441908jes",
        "key_parameters": {
            "Nominal cell capacity [A.h]": 17.0,
            "Lower voltage cut-off [V]": 1.75,
            "Upper voltage cut-off [V]": 2.42,
            "Electrode height [m]": 0.137,
            "Electrode width [m]": 0.207,
            "Negative electrode thickness [m]": 1.1e-03,
            "Separator thickness [m]": 1.1e-03,
            "Positive electrode thickness [m]": 1.3e-03,
            "Negative electrode porosity": 0.5,
            "Positive electrode porosity": 0.5,
            "Separator porosity": 0.6,
            "Negative electrode surface area to volume ratio [m-1]": 1.5e+05,
            "Positive electrode surface area to volume ratio [m-1]": 5e+05,
            "Initial concentration in electrolyte [mol.m-3]": 4740.0,
            "Reference temperature [K]": 298.15,
            "Negative electrode material": "Lead (Pb)",
            "Positive electrode material": "Lead dioxide (PbO2)",
            "Electrolyte": "Sulfuric acid (H2SO4)",
        },
        "special_features": [
            "Lead-acid battery chemistry",
            "BBOXX cell parameters",
            "Porous-electrode theory",
            "Asymptotic analysis",
        ],
        "validated_conditions": {
            "temperature_range": "25°C",
            "c_rate_range": "C/20 to C/5",
        },
    },
}


def get_parameter_set_info(name: str) -> Optional[Dict[str, Any]]:
    """Get detailed information about a parameter set."""
    return PARAMETER_SET_DETAILS.get(name)


def get_parameter_sets_for_chemistry(chemistry: str) -> List[str]:
    """Get list of parameter sets available for a given chemistry."""
    return [
        name for name, details in PARAMETER_SET_DETAILS.items()
        if details.get("chemistry") == chemistry
    ]


def get_chemistry_defaults(chemistry: str) -> Optional[Dict[str, Any]]:
    """Get default parameters and characteristics for a chemistry."""
    return CHEMISTRY_DEFAULTS.get(chemistry)


def list_all_parameter_sets() -> Dict[str, Dict[str, Any]]:
    """Get summary of all available parameter sets."""
    return {
        name: {
            "chemistry": details.get("chemistry"),
            "cell_type": details.get("cell_type"),
            "cell_format": details.get("cell_format", "N/A"),
            "reference": details.get("reference"),
        }
        for name, details in PARAMETER_SET_DETAILS.items()
    }
